application: yuzu
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers match in order, put above the default handler.
handlers:
- url: /codemirror
  static_dir: static/codemirror

- url: /skulpt
  static_dir: static/skulpt

- url: /img
  static_dir: static/img

- url: .*
  script: main.app
